### ISSUE TITLE
MCIO View Products and Services Roadmap (first draft)

### ISSUE THREAD

**Issue by brockknudsen** [bcgov/aspb-planning#53]

**Comment by kelpisland** [comment]
Involve Jackie and Mary. Touch base with Derek for details.

**Comment by scayzer** [comment]
For TS projects that will add/change products or services in our catalog, we need a roadmap to support collaboration with MCIO's and ministry ADM's.

Objective(s):
Increase reporting capabilities on TS Service Development Lifecycle for our BRM's and ministry service consumers
